splitter: sentence_text_splitter_LC #token_text_splitter #sentence_text_splitter #token_text_splitter #sentence_text_splitter_LC  #semantic_splitter
embedding: sky   #opnenai,huggingface, sky,sentence_text_splitter_LC only supports HF models
metadata:
  - default
  # - custom
reader:
  # - file
  - scrapeddatareader
  #- scrapyreader
  # - sharepointreader

adjacent_chunks: true

sentence_text_splitter:
  chunk_size: 256
  chunk_overlap: 0


sentence_text_splitter_LC:
  chunk_size: 256
  chunk_overlap: 0


token_text_splitter:
  chunk_size: 256
  chunk_overlap: 0

mlflow:
  experiment: sharmi-ingestion-sep2-GI

huggingface:
  model: "BAAI/bge-large-en-v1.5"

# openai:
#   model: "text-embedding-ada-002"
#   llmkey: 

sky:
  embedding_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2lyZWVzaGEtbWFuZGF2YSIsInR5cGUiOiJhcGkiLCJpZCI6Ii9kZXBsb3ltZW50L2JnZWxhcmdlZGV2LyJ9.mqA6DLbTqK2JufmPaSSKHo6NvcIxhtzaCJxcaDANYwA"
  embedding_url: "http://54.160.139.85:30002/v1/"
  batch_size: 10

# sky:
#   embedding_key: 
#   embedding_url: 
#   batch_size: 10

# custom:
#   adjacent_chunks: False
#   extractor_path: <absolute path to .py file>

scrapeddatareader:        # make sure the folder has a mapping file named "url_file_name_map.json" for links of pdf files
  inputs:
    loader_args:
      input_dir: /home/data/GI_Data_Aug16
      exclude_hidden: true 
      raise_on_error: true 
    data_args:
      doc_source: gi
      state_category: NV 
      designation_category: Consumer 
      topic_category: general 

scrapyreader:
  inputs:
    loader_args:
      test1: ""
    data_args:
      spiders:
        # myspider:
        # - path: /home/configs/spiders/quotess.py
        #   url: 
        #     - "https://quotes.toscrape.com/page/1/"
        #     - "https://quotes.toscrape.com/page/2/"
        # Acasignspider:
        #   - url: "https://acasignups.net"
         irs:
           - url: "https://www.irs.gov/affordable-care-act"
             # pennie:                                                           
             # - url: "https://agency.pennie.com/about-us/"
        # nevadaa:                                                            
        #   - url: "https://www.nevadahealthlink.com/sshix/"
        # va:                                                                 
        #   - url: "https://www.marketplace.virginia.gov/"
        # penniefaq:
        #   - url: "https://help.pennie.com/hc/en-us/sections/360008569673-Customer"
file:
  inputs:
    loader_args:
      input_dir: /home/sai-neralla/llamaid_configs/Ndadoc
      recursive: true
      exclude_hidden: true
      raise_on_error: true
sharepointreader:
  inputs:
    loader_args:
      client_id: 
      client_secret: 
      tenant_id: 
      sharepoint_site_id: 
      drive_id: 
      sharepoint_site_name: ""
      sharepoint_folder_path: ""
    data_args:     
      doc_source: 
      state_category: 
      designation_category: 
      topic_category:
